trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    if ! command -v gcloud &> /dev/null
    then
        echo "Google Cloud SDK not found, installing specific version..."
        # The script to invoke GoogleCloudSdkTool task
    else
        echo "Google Cloud SDK already installed, checking version..."
        gcloud --version
    fi
  displayName: 'Check and Install Google Cloud SDK'

- task: GoogleCloudSdkTool@1
  condition: and(succeeded(), eq(variables['GCloudSDKInstalled'], 'false'))
  inputs:
    versionSpec: '315.x'

- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'edtech-azure-pipepine-gcp-key.json'

- task: DownloadSecureFile@1
  name: sshKey
  inputs:
    secureFile: 'gcp-webserver-ssh-key'


- bash: |
    gcloud auth activate-service-account --key-file $(gcpKey.secureFilePath)
    gcloud config set project secret-air-408514
  displayName: 'Authenticate to GCP and Set Project'

- bash: |
    gcloud compute instances list
    chmod 600 $(sshKey.secureFilePath)
    gcloud compute ssh webserver --zone asia-south1-c --command "node -v" --ssh-key-file=$(sshKey.secureFilePath)
  displayName: 'List Instances and SSH into VM'
